name: docx_template
description: A Docx template engine.
version: 0.4.1
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.4
  xml: ^6.5.0
  collection: ^1.19.1
  path: ^1.9.1
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
